<?php
/**
 * @file
 * Crazier add-ons for profiler builder
 */

/**
 * Implements hook_menu().
 */
function drush_recipes_profiler_builder_menu() {
  $items = array();
  $items['admin/config/development/profiler_builder/drush_recipes'] = array(
    'title' => 'Drush recipes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_drush_recipes_profiler_builder_settings'),
    'description' => 'Drush recipe recording console.',
    'access arguments' => array('administer profiler builder'),
    'file' => 'drush_recipes_profiler_builder.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  return $items;
}
